# Generated by Django 6.0.2 on 2026-02-18 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
